services:
  dockerhell:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    privileged: true
    volumes:
      - .:/workspace  
      - /home/tomas/.cache/ccache:/workspace/.ccache
      - /home/tomas/.conan2-dockerhell:/root/.conan2:rw
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: >
      /bin/bash